### ISSUE TITLE
GIF isn't playing correctly

### ISSUE THREAD

**Issue by Kwaver** [gwaredd/mgGif#1]
Works for most of the gif's I've tried but one particular one isn't playing correctly. 
It look like it's the delay that is being set as 0 when loaded which is incorrect. The actual delay per frame is around 10 1/100ths (0.1 ms) so it's not being parsed correctly.  Plays fine in a web browser.
Has this been encountered before? 
![HauntedHouse](https://user-images.githubusercontent.com/6883005/107636585-c30ef980-6c64-11eb-9c8c-be6a55904188.gif)

**Comment by gwaredd** [comment]
The file is (probably) being parsed correctly.

According to the [GIF specification](https://www.w3.org/Graphics/GIF/spec-gif89a.txt), for a delay of 0 you are meant to skip that frame. However, as with all the best standards, there can sometimes be a difference in the specification and the real world implementation.

In this case it turns out that different browsers do different things. You can find a write up [here](https://www.deviantart.com/humpy77/journal/Frame-Delay-Times-for-Animated-GIFs-214150546) which goes into the detail.

So I guess you can either edit the file and stick in the delay you want for that frame or hardcode in the delay you want in code. mgGif just parses the data, the idiosyncrasies of the format for the playback is left for the joys of the consumer ;)

**Comment by Kwaver** [comment]
Thank you for the explanation and would make sense that in this instance, a delay of 10 1/100th's works as it matches up with Internet Explorer.
